template:
  image: slidewiki/userservice
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=userservice.experimental.slidewiki.org
    - SMTP_PORT=25
    - SMTP_HOST=localhost
    - SMTP_FROM=me@hostername.org
#    - SMTP_CLIENTNAME=
#    - APIKey=
    - URL_ACTIVITIESSERVICE=http://activitiesservice.experimental.slidewiki.org
