template:
  image: slidewiki/userservice
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=userservice.experimental.slidewiki.org
    - SMTP_PORT=25
    - SMTP_HOST=localhost
    - SMTP_FROM=me@hostername.org
#    - SMTP_CLIENTNAME=
#    - APIKey=
    - URL_PLATFORM=http://platform.experimental.slidewiki.org
    - URL_ACTIVITIESSERVICE=http://activitiesservice.experimental.slidewiki.org
#     - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file, not needed here, because of docker-compose v1
  volumes:
    - /data/slidewiki-deployment/docker-compose/providerConfig.json:/nodeApp/config.json:ro
