// Generated by CoffeeScript 1.10.0
'use strict';
(function() {
  let Consumer, exports;

  Consumer = (function() {
    function Consumer() {
      console.error('Consumer Not Implemented');
      false;
    }

    return Consumer;

  })();

  exports = module.exports = Consumer;

}).call(this);
